---
- name: Install Java
  hosts: all
  tasks:
    - name: Set facts for Java 11 vars
      set_fact:
        java_home: "/opt/jdk/{{ java_jdk_version }}"
      tags: java
    - name: Upload .tar.gz file containing binaries from local storage
      copy:
        src: "{{ java_oracle_jdk_package }}"
        dest: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
      register: download_java_binaries
      until: download_java_binaries is succeeded
      tags: java
    - name: Ensure installation dir exists
      become: true
      file:
        state: directory
        path: "{{ java_home }}"
      tags: java
    - name: Extract java in the installation directory
      become: true
      unarchive:
        copy: false
        src: "/tmp/jdk-{{ java_jdk_version }}.tar.gz"
        dest: "{{ java_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ java_home }}/bin/java"
      tags:
        - java
    - name: Export environment variables
      become: true
      template:
        src: jdk.sh.j2
        dest: /etc/profile.d/jdk.sh
      tags: java
- name: Install Elasticsearch
  hosts: elasticsearch
  tasks:
    - name: Set facts for Elastic 8 vars
      set_fact:
        elastic_home: "/opt/elastisearch/{{ elastic_version }}"
      tags: elastic
    - name: Upload .tar.gz file containing binaries from local storage
      copy:
        src: "{{ elasticsearch_package }}"
        dest: "/tmp/elasticsearch-{{ elastic_version }}.tar.gz"
      register: download_elasticsearch_binaries
      until: download_elasticsearch_binaries is succeeded
      tags: elastic
    - name: Ensure installation dir exists
      become: true
      file:
        state: directory
        path: "{{ elastic_home }}"
      tags: elastic
    - name: Extract elasticsearch in the installation directory
      become: true
      unarchive:
        copy: false
        src: "/tmp/elasticsearch-{{ elastic_version }}.tar.gz"
        dest: "{{ elastic_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ elastic_home }}/bin/elasticsearch"
      tags:
        - elastic
    - name: Export environment variables
      become: true
      template:
        src: elk.sh.j2
        dest: /etc/profile.d/elk.sh
      tags: elastic
- name: Install Kibana
  hosts: kibana_host
  tasks:
    - name: Set facts for Kibana 7 vars
      set_fact:
        kibana_home: "/opt/kibana/{{ kibana_version }}"
      tags: kibana
    - name: Upload .tar.gz file containing binaries from local storage
      copy:
        src: "{{ kibana_package }}"
        dest: "/tmp/kibana-{{ kibana_version }}.tar.gz"
      register: download_kibana_binaries
      until: download_kibana_binaries is succeeded
      tags: kibana
    - name: Ensure installation dir exists
      become: true
      file:
        state: directory
        path: "{{ kibana_home }}"
      tags: kibana
    - name: Extract kibana in the installation directory
      become: true
      unarchive:
        copy: false
        src: "/tmp/kibana-{{ kibana_version }}.tar.gz"
        dest: "{{ kibana_home }}"
        extra_opts: [--strip-components=1]
        creates: "{{ kibana_home }}/bin/kibana"
      tags:
        - kibana
    - name: Export environment variables
      become: true
      template:
        src: kbn.sh.j2
        dest: /etc/profile.d/kbn.sh
      tags: kibana
